apiVersion: v1
kind: Service
metadata:
  name: quickbite-service
  namespace: quickbite
  labels:
    app: quickbite
spec:
  type: NodePort
  selector:
    app: quickbite
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
      name: http
